apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    env: prod
    app: java-app
  name: rs-java
  namespace: prodns
  annotations:
    ecr-registry: 777014042292.dkr.ecr.ap-south-1.amazonaws.com/springpetclinic/java
spec:
  replicas: 3
  minReadySeconds: 6
  selector:
    matchLabels:
      app: spc-java
  template:
    metadata:
      name: javapod
      labels:
        app: spc-java
    spec:
      containers:
        - name: java-pod
          image: 777014042292.dkr.ecr.ap-south-1.amazonaws.com/springpetclinic/java:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            requests:
              cpu: "1800m" #1.8 CPU --m5.large - 2 CPU
              memory: "7500Mi"  # 7.5 GB RAM --m5.large - 8 GB
            limits:
              cpu: "1800m"        
              memory: "7500Mi" 

